services:
  postgres_auth:
    image: postgres:16-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password_change_in_prod_123
      POSTGRES_DB: authdb
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - transcriber-network
    restart: unless-stopped

  postgres_transcriber:
    image: postgres:16-alpine
    container_name: postgres_transcriber
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: transcriber_password_change_in_prod_123
      POSTGRES_DB: transcriberdb
    volumes:
      - postgres_transcriber_data:/var/lib/postgresql/data
    networks:
      - transcriber-network
    restart: unless-stopped

  redis_container:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - transcriber-network
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: backend/services/auth/Dockerfile
    container_name: auth_service
    expose:
      - "8000"
    volumes:
      - ./backend/services/auth/keys:/app/keys
      - ./backend/services/auth/app:/app/app
      - ./backend/shared:/app/backend/shared
    env_file:
      - ./backend/services/auth/.env
    environment:
      POSTGRES_AUTH_HOST: postgres_auth
      POSTGRES_AUTH_PORT: 5432
      POSTGRES_AUTH_DB: authdb
      POSTGRES_AUTH_USER: postgres
      POSTGRES_AUTH_PASSWORD: auth_password_change_in_prod_123
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
    depends_on:
      - postgres_auth
      - redis_container
    restart: unless-stopped
    networks:
      - transcriber-network

  transcriber:
    build:
      context: .
      dockerfile: backend/services/transcriber/Dockerfile
    container_name: transcriber_backend
    expose:
      - "8000"
    volumes:
      - ./backend/services/auth/keys:/app/keys
      - ./backend/shared:/app/backend/shared
    env_file:
      - ./backend/services/transcriber/.env
    environment:
      POSTGRES_TRANSCRIBER_HOST: postgres_transcriber
      POSTGRES_TRANSCRIBER_PORT: 5432
      POSTGRES_TRANSCRIBER_DB: transcriberdb
      POSTGRES_TRANSCRIBER_USER: postgres
      POSTGRES_TRANSCRIBER_PASSWORD: transcriber_password_change_in_prod_123
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
    depends_on:
      - postgres_transcriber
      - redis_container
    restart: unless-stopped
    networks:
      - transcriber-network

  # Nginx с HTTPS и проксированием
  frontend:
    build: ./nginx
    container_name: transcriber_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth
      - transcriber
    restart: unless-stopped
    networks:
      - transcriber-network

networks:
  transcriber-network:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_transcriber_data:
